export const role = "admin";

export const menuItems = [
  {
    title: "Menú",
    items: [
      {
        icon: "/home.png",
        label: "Home",
        href: "/",
        visible: ["admin", "teacher", "student", "parent"],
      },
      {
        icon: "/teacher.png",
        label: "Maestros",
        href: "/list/teachers",
        visible: ["admin", "teacher"],
      },
      {
        icon: "/student.png",
        label: "Estudiantes",
        href: "/list/students",
        visible: ["admin", "teacher"],
      },
      {
        icon: "/parent.png",
        label: "Padres",
        href: "/list/parents",
        visible: ["admin", "teacher"],
      },
      {
        icon: "/subject.png",
        label: "Materias",
        href: "/list/subjects",
        visible: ["admin"],
      },
      {
        icon: "/class.png",
        label: "Salones",
        href: "/list/classes",
        visible: ["admin", "teacher"],
      },
      {
        icon: "/lesson.png",
        label: "Clases",
        href: "/list/lessons",
        visible: ["admin", "teacher"],
      },
      {
        icon: "/exam.png",
        label: "Exámanes",
        href: "/list/exams",
        visible: ["admin", "teacher", "student", "parent"],
      },
      {
        icon: "/assignment.png",
        label: "Tareas",
        href: "/list/assignments",
        visible: ["admin", "teacher", "student", "parent"],
      },
      {
        icon: "/result.png",
        label: "Resultados",
        href: "/list/results",
        visible: ["admin", "teacher", "student", "parent"],
      },
      {
        icon: "/attendance.png",
        label: "Asistencia",
        href: "/list/attendance",
        visible: ["admin", "teacher", "student", "parent"],
      },
      {
        icon: "/calendar.png",
        label: "Eventos",
        href: "/list/events",
        visible: ["admin", "teacher", "student", "parent"],
      },
      {
        icon: "/message.png",
        label: "Mensajes",
        href: "/list/messages",
        visible: ["admin", "teacher", "student", "parent"],
      },
      {
        icon: "/announcement.png",
        label: "Anuncios",
        href: "/list/announcements",
        visible: ["admin", "teacher", "student", "parent"],
      },
    ],
  },
  {
    title: "Otros",
    items: [
      {
        icon: "/profile.png",
        label: "Perfil",
        href: "/profile",
        visible: ["admin", "teacher", "student", "parent"],
      },
      {
        icon: "/setting.png",
        label: "Configuración",
        href: "/settings",
        visible: ["admin", "teacher", "student", "parent"],
      },
      {
        icon: "/logout.png",
        label: "Cerrar sesión",
        href: "/logout",
        visible: ["admin", "teacher", "student", "parent"],
      },
    ],
  },
];

export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2026, 4, 1, 8, 0),
    end: new Date(2026, 4, 1, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 4, 1, 9, 0),
    end: new Date(2026, 4, 1, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 4, 1, 10, 0),
    end: new Date(2026, 4, 1, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 4, 5, 11, 0),
    end: new Date(2026, 4, 5, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2026, 4, 5, 13, 0),
    end: new Date(2026, 4, 5, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2026, 4, 5, 14, 0),
    end: new Date(2026, 4, 5, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 4, 6, 9, 0),
    end: new Date(2026, 4, 6, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 4, 6, 10, 0),
    end: new Date(2026, 4, 6, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 4, 6, 11, 0),
    end: new Date(2026, 4, 6, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2026, 4, 7, 14, 0),
    end: new Date(2026, 4, 7, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2026, 4, 7, 8, 0),
    end: new Date(2026, 4, 7, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 4, 7, 10, 0),
    end: new Date(2026, 4, 7, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2026, 4, 7, 13, 0),
    end: new Date(2026, 4, 7, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2026, 4, 7, 14, 0),
    end: new Date(2026, 4, 7, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 4, 7, 9, 0),
    end: new Date(2026, 4, 7, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 4, 7, 10, 0),
    end: new Date(2026, 4, 7, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 4, 7, 11, 0),
    end: new Date(2026, 4, 7, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2026, 4, 8, 14, 0),
    end: new Date(2026, 4, 8, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2026, 4, 8, 8, 0),
    end: new Date(2026, 4, 8, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 4, 8, 9, 0),
    end: new Date(2026, 4, 8, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 4, 8, 11, 0),
    end: new Date(2026, 4, 8, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2026, 4, 8, 13, 0),
    end: new Date(2026, 4, 8, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2026, 4, 8, 14, 0),
    end: new Date(2026, 4, 8, 14, 45),
  },
];

export const teachersData = [
  {
    id: 1,
    teacherId: "7894561230",
    name: "Carlos Mendoza",
    email: "carlos.mendoza@gmail.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "6121234567",
    subjects: ["Matemáticas", "Geometría"],
    classes: ["1B", "2A", "3C"],
    address: "Av. Insurgentes 123, Ciudad de México, México",
  },
  {
    id: 2,
    teacherId: "4561237890",
    name: "María Fernanda López",
    email: "maria.lopez@gmail.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "5512345678",
    subjects: ["Física", "Química"],
    classes: ["5A", "4B", "3C"],
    address: "Calle 45 #210, Ciudad de México, México",
  },
  {
    id: 3,
    teacherId: "3216549870",
    name: "José Ramírez",
    email: "jose.ramirez@gmail.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9987654321",
    subjects: ["Biología"],
    classes: ["5A", "4B", "3C"],
    address: "Av. Siempre Viva 742, Ciudad de México, México",
  },
  {
    id: 4,
    teacherId: "1597534862",
    name: "Luis Herrera",
    email: "luis.herrera@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "3412345678",
    subjects: ["Historia"],
    classes: ["5A", "4B", "3C"],
    address: "Calle San Martín 456, Ciudad de México, México",
  },
  {
    id: 5,
    teacherId: "8523697410",
    name: "Ana Torres",
    email: "ana.torres@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "2223456789",
    subjects: ["Música", "Historia"],
    classes: ["5A", "4B", "3C"],
    address: "Av. Reforma 789, Ciudad de México, México",
  },
  {
    id: 6,
    teacherId: "9632587410",
    name: "Sofía Castillo",
    email: "sofia.castillo@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "8091234567",
    subjects: ["Física"],
    classes: ["5A", "4B", "3C"],
    address: "Calle Duarte 321, Ciudad de México, México",
  },
  {
    id: 7,
    teacherId: "1472583690",
    name: "Diego Morales",
    email: "diego.morales@gmail.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "50312345678",
    subjects: ["Inglés", "Español"],
    classes: ["5A", "4B", "3C"],
    address: "Colonia Escalón, Ciudad de México, México",
  },
  {
    id: 8,
    teacherId: "3692581470",
    name: "Valentina Rojas",
    email: "valentina.rojas@gmail.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "56912345678",
    subjects: ["Matemáticas", "Geometría"],
    classes: ["5A", "4B", "3C"],
    address: "Av. Providencia 1234, Ciudad de México, México",
  },
  {
    id: 9,
    teacherId: "2581473690",
    name: "Ricardo Gómez",
    email: "ricardo.gomez@gmail.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "50498765432",
    subjects: ["Literatura", "Inglés"],
    classes: ["5A", "4B", "3C"],
    address: "Colonia Palmira, Ciudad de México, México",
  },
  {
    id: 10,
    teacherId: "7412589630",
    name: "Andrés Paredes",
    email: "andres.paredes@gmail.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "593987654321",
    subjects: ["Biología"],
    classes: ["5A", "4B", "3C"],
    address: "Av. Amazonas 456, Ciudad de México, México",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "20230001",
    name: "Luis Hernández",
    email: "luis.hernandez@gmail.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "5512345678",
    grade: 5,
    class: "1B",
    address: "Av. Insurgentes Sur 1450, Benito Juárez, Ciudad de México",
  },
  {
    id: 2,
    studentId: "20230002",
    name: "Mariana García",
    email: "mariana.garcia@gmail.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "5523456789",
    grade: 5,
    class: "5A",
    address: "Calle Madero 210, Centro, Ciudad de México",
  },
  {
    id: 3,
    studentId: "20230003",
    name: "José López",
    email: "jose.lopez@gmail.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "5534567890",
    grade: 5,
    class: "5A",
    address: "Av. Tláhuac 980, Iztapalapa, Ciudad de México",
  },
  {
    id: 4,
    studentId: "20230004",
    name: "Fernanda López",
    email: "fernanda.lopez@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "5545678901",
    grade: 5,
    class: "5A",
    address: "Av. Tláhuac 980, Iztapalapa, Ciudad de México",
  },
  {
    id: 5,
    studentId: "20230005",
    name: "Diego Ramírez",
    email: "diego.ramirez@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "5556789012",
    grade: 5,
    class: "5A",
    address: "Av. Universidad 3000, Coyoacán, Ciudad de México",
  },
  {
    id: 6,
    studentId: "20230006",
    name: "Valeria Torres",
    email: "valeria.torres@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "5567890123",
    grade: 5,
    class: "5A",
    address: "Av. Revolución 850, Álvaro Obregón, Ciudad de México",
  },
  {
    id: 7,
    studentId: "20230007",
    name: "Carlos Sánchez",
    email: "carlos.sanchez@gmail.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "5578901234",
    grade: 5,
    class: "5A",
    address: "Eje Central Lázaro Cárdenas 500, Cuauhtémoc, Ciudad de México",
  },
  {
    id: 8,
    studentId: "20230008",
    name: "Sofía Morales",
    email: "sofia.morales@gmail.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "5589012345",
    grade: 5,
    class: "5A",
    address: "Av. Patriotismo 600, Benito Juárez, Ciudad de México",
  },
  {
    id: 9,
    studentId: "20230009",
    name: "Jorge Castro",
    email: "jorge.castro@gmail.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "5590123456",
    grade: 5,
    class: "5A",
    address: "Av. Zaragoza 1200, Iztacalco, Ciudad de México",
  },
  {
    id: 10,
    studentId: "20230010",
    name: "Andrea Flores",
    email: "andrea.flores@gmail.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "5511122233",
    grade: 5,
    class: "5A",
    address: "Av. Chapultepec 250, Cuauhtémoc, Ciudad de México",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Hernández",
    students: ["Luis Hernández"],
    email: "john@gmail.com",
    phone: "1234567890",
    address: "Av. Insurgentes Sur 1450, Benito Juárez, Ciudad de México",
  },
  {
    id: 2,
    name: "Linda García",
    students: ["Mariana García"],
    email: "linda@gmail.com",
    phone: "1234567890",
    address: "Calle Madero 210, Centro, Ciudad de México",
  },
  {
    id: 3,
    name: "María Ramírez",
    students: ["Diego Ramírez"],
    email: "mary@gmail.com",
    phone: "1234567890",
    address: "Av. Universidad 3000, Coyoacán, Ciudad de México",
  },
  {
    id: 4,
    name: "Jorge López",
    students: ["José López", "Fernanda López"],
    email: "jorge@gmail.com",
    phone: "1234567890",
    address: "Av. Tláhuac 980, Iztapalapa, Ciudad de México",
  },
  {
    id: 5,
    name: "Guadalupe Torres",
    students: ["Valeria Torres"],
    email: "lupe@gmail.com",
    phone: "1234567890",
    address: "Av. Revolución 850, Álvaro Obregón, Ciudad de México",
  },
  {
    id: 6,
    name: "Roberto Sánchez",
    students: ["Carlos Sánchez"],
    email: "robert@gmail.com",
    phone: "1234567890",
    address: "Eje Central Lázaro Cárdenas 500, Cuauhtémoc, Ciudad de México",
  },
  {
    id: 7,
    name: "María José Morales",
    students: ["Sofía Morales"],
    email: "mjose@gmail.com",
    phone: "1234567890",
    address: "Av. Patriotismo 600, Benito Juárez, Ciudad de México",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Jorge Castro"],
    email: "ophelia@gmail.com",
    phone: "1234567890",
    address: "Av. Zaragoza 1200, Iztacalco, Ciudad de México",
  },
  {
    id: 9,
    name: "Ana Flores",
    students: ["Andrea Flores"],
    email: "anaflores@gmail.com",
    phone: "1234567890",
    address: "Av. Chapultepec 250, Cuauhtémoc, Ciudad de México",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Matemáticas",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "Inglés",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Física",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Química",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biología",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "Historia",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geografía",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Artes",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Música",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literatura",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Matemáticas",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "Inglés",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Ciencias",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Ciencias Sociales",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Artes",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Música",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "Historia",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geografía",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Física",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Química",
    class: "4B",
    teacher: "Julia Pittman",
  },
];
